spring.application.name=social
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.hooekbpbpgrxjlczgml
spring.datasource.password=tonay.cs@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
cloudinary.cloud-name=djnwuceqc
cloudinary.api-key=866653183174259
cloudinary.api-secret=4dHC-n2sMu8_u_NnZG7ScuMM1Is

stream.api.key=efcwmjstj8vu
stream.api.secret=4qr8yhpt6r9f4bc5dr9bemk9paz4pejhq47mtwmgdbmuxn2e7pma5ssbxwnykv9y
